<a href="https://colab.research.google.com/github/JinRu1121/data-science-toolkit/blob/main/Numpy_Week_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
n4 = np.eye(5)
print(n4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
num4 = np.random.random((2, 2))
print(num4)

[[0.8951752  0.27556738]
 [0.25515142 0.92370969]]
