<a href="https://colab.research.google.com/github/JinRu1121/data-science-toolkit/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. Create a numpy array of size 2 x 2

arr_2x2 = np.array([[1, 2],
                    [3, 4]])
print("--- Task 1: 2x2 Array ---")
print(arr_2x2)
print("\n")


# 2. Create a random numpy array of size 3 x 4

arr_random_3x4 = np.random.rand(3, 4)
print("--- Task 2: 3x4 Random Array ---")
print(arr_random_3x4)
print("\n")


# 3. Create a numpy array of ones and a numpy array of zeroes

arr_ones = np.ones((3, 3))
arr_zeros = np.zeros((3, 3))
print("--- Task 3: Ones and Zeros Arrays ---")
print("Array of ones:")
print(arr_ones)
print("Array of zeros:")
print(arr_zeros)
print("\n")


# 4. Create a random numpy array of size 6x3 and transpose it

arr_6x3 = np.random.rand(6, 3)
arr_transposed = arr_6x3.T
print("--- Task 4: Transpose ---")
print("Original 6x3 array:")
print(arr_6x3)
print("Transposed 3x6 array:")
print(arr_transposed)
print("\n")


# 5. Create two random numpy arrays of size n x p and p x m and compute the dot product

# n = 4
# p = 3
# m = 5
# So we need one array of (4, 3) and one of (3, 5).
n = 4
p = 3
m = 5

A = np.random.rand(n, p) # Creates a 4x3 array
B = np.random.rand(p, m) # Creates a 3x5 array



dot_product = np.dot(A, B)

print("--- Task 5: Dot Product ---")
print("Array A (shape 4x3):")
print(A)
print("Array B (shape 3x5):")
print(B)
print("Dot Product (shape 4x5):")
print(dot_product)

--- Task 1: 2x2 Array ---
[[1 2]
 [3 4]]


--- Task 2: 3x4 Random Array ---
[[8.57933231e-01 3.89312115e-01 6.38584920e-01 7.64973571e-01]
 [1.98303389e-01 5.19325899e-01 8.90970851e-01 4.89369711e-04]
 [1.16290359e-01 8.09109309e-01 9.49555405e-01 8.42671259e-01]]


--- Task 3: Ones and Zeros Arrays ---
Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


--- Task 4: Transpose ---
Original 6x3 array:
[[0.83062135 0.11244223 0.68926642]
 [0.24869172 0.69171915 0.16488   ]
 [0.4875342  0.43461562 0.40363549]
 [0.35406357 0.49208489 0.91125721]
 [0.91637746 0.63536154 0.17128325]
 [0.86576576 0.66243682 0.1390642 ]]
Transposed 3x6 array:
[[0.83062135 0.24869172 0.4875342  0.35406357 0.91637746 0.86576576]
 [0.11244223 0.69171915 0.43461562 0.49208489 0.63536154 0.66243682]
 [0.68926642 0.16488    0.40363549 0.91125721 0.17128325 0.1390642 ]]


--- Task 5: Dot Product ---
Array A (shape 4x3):
[[0.71853926 0.95573454 0.20933475]
 [0.418